//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportStudentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTSV
    {
        public string MSSV { get; set; }
        public string HoLot { get; set; }
        public string Ten { get; set; }
        public string TenLop { get; set; }
        public string TenNganh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDTSV { get; set; }
        public string TenHDT { get; set; }
        public string emailSV { get; set; }
    }
}
